# Generated by Django 3.1.7 on 2021-07-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0003_auto_20210611_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_name',
        ),
    ]
